import { Event } from '@/types';

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Birthday Party',
    category: 'birthday',
    description: 'AI-generated birthday themes, balloon decoration, cake placement, and seating layouts.',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800',
    price: 15000,
    duration: '4-6 hours',
    rating: 4.8,
    reviewCount: 124,
    features: ['Balloon Decoration', 'Cake Setup', 'Theme Design', 'AI Layout Planning']
  },
  {
    id: '2',
    title: 'Wedding Party',
    category: 'wedding',
    description: 'Traditional and modern wedding planning with AI-powered stage, seating, and décor previews.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
    price: 150000,
    duration: '1-2 days',
    rating: 4.9,
    reviewCount: 287,
    features: ['Stage Design', 'Seating Arrangement', 'Décor Preview', 'Traditional Setup']
  },
  {
    id: '3',
    title: 'Reception Party',
    category: 'reception',
    description: 'Elegant reception layouts with lighting optimization and guest movement planning.',
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800',
    price: 80000,
    duration: '5-8 hours',
    rating: 4.7,
    reviewCount: 156,
    features: ['Lighting Design', 'Guest Flow', 'Table Setup', 'Ambiance Planning']
  },
  {
    id: '4',
    title: 'Engagement Ceremony',
    category: 'engagement',
    description: 'Ring ceremony planning with AI-generated stage and guest seating ideas.',
    image: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800',
    price: 35000,
    duration: '3-5 hours',
    rating: 4.6,
    reviewCount: 98,
    features: ['Stage Setup', 'Ring Presentation', 'Guest Seating', 'Photo Areas']
  },
  {
    id: '5',
    title: 'Baby Shower',
    category: 'babyshower',
    description: 'Soft-themed baby shower decorations with AI layout suggestions.',
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
    price: 20000,
    duration: '3-4 hours',
    rating: 4.8,
    reviewCount: 112,
    features: ['Theme Decoration', 'Game Areas', 'Food Setup', 'Gift Display']
  },
  {
    id: '6',
    title: 'Corporate Event',
    category: 'corporate',
    description: 'Professional conference planning with AI-generated stage and seating arrangements.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    price: 100000,
    duration: '1 day',
    rating: 4.7,
    reviewCount: 203,
    features: ['Conference Setup', 'Tech Integration', 'Professional Layout', 'Branding']
  },
  {
    id: '7',
    title: 'Graduation Party',
    category: 'graduation',
    description: 'Modern graduation party themes and AI-based layout planning.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    price: 25000,
    duration: '4-5 hours',
    rating: 4.5,
    reviewCount: 87,
    features: ['Theme Setup', 'Photo Booth', 'Achievement Display', 'Memory Wall']
  },
  {
    id: '8',
    title: 'Festival Celebration',
    category: 'festival',
    description: 'Diwali, Christmas, New Year and other festivals with cultural AI themes.',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800',
    price: 40000,
    duration: '6-8 hours',
    rating: 4.9,
    reviewCount: 176,
    features: ['Cultural Décor', 'Traditional Setup', 'Lighting Design', 'Food Court']
  },
  {
    id: '9',
    title: 'Housewarming Ceremony',
    category: 'housewarming',
    description: 'Traditional griha pravesh planning with modern welcome décor and guest hospitality flow.',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
    price: 28000,
    duration: '4-6 hours',
    rating: 4.6,
    reviewCount: 74,
    features: ['Pooja Setup', 'Entrance Décor', 'Guest Seating', 'Catering Coordination']
  },
  {
    id: '10',
    title: 'Cultural Night Showcase',
    category: 'cultural',
    description: 'Stage-first planning for dance, music, and cultural programs with crowd-flow intelligence.',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    price: 65000,
    duration: '5-7 hours',
    rating: 4.8,
    reviewCount: 133,
    features: ['Stage Management', 'Green Room Planning', 'Audience Layout', 'Sound-Light Sync']
  },
  {
    id: '11',
    title: 'Destination Wedding Experience',
    category: 'wedding',
    description: 'Full destination wedding blueprint with multi-day logistics, décor themes, and vendor alignment.',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
    price: 280000,
    duration: '2-3 days',
    rating: 4.9,
    reviewCount: 201,
    features: ['Multi-Day Timeline', 'Guest Logistics', 'Venue Styling', 'Vendor Orchestration']
  },
  {
    id: '12',
    title: 'Kids Theme Birthday Carnival',
    category: 'birthday',
    description: 'Colorful birthday carnival setup with activity zones, games, and safe kid-friendly layouts.',
    image: 'https://images.unsplash.com/photo-1464349153735-7db50ed83c84?w=800',
    price: 22000,
    duration: '3-5 hours',
    rating: 4.7,
    reviewCount: 118,
    features: ['Activity Zones', 'Game Corner', 'Photo Booth', 'Theme Styling']
  },
  {
    id: '13',
    title: 'Premium Engagement Soiree',
    category: 'engagement',
    description: 'Elegant engagement planning with premium floral styling, stage concepts, and spotlight moments.',
    image: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800',
    price: 55000,
    duration: '4-6 hours',
    rating: 4.8,
    reviewCount: 109,
    features: ['Premium Stage Design', 'Floral Styling', 'Family Lounge', 'Photography Flow']
  },
  {
    id: '14',
    title: 'Grand Reception Gala',
    category: 'reception',
    description: 'Large-capacity reception production with entrance effects, banquet layout, and smooth stage transitions.',
    image: 'https://images.unsplash.com/photo-1519167758481-83f29c8fc7fa?w=800',
    price: 120000,
    duration: '6-8 hours',
    rating: 4.8,
    reviewCount: 164,
    features: ['Grand Entry Effects', 'Banquet Layout', 'Live Stage Flow', 'VIP Seating']
  },
  {
    id: '15',
    title: 'Startup Launch Event',
    category: 'corporate',
    description: 'Product launch event design with keynote stage, media zones, and branded guest experience.',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
    price: 90000,
    duration: '1 day',
    rating: 4.7,
    reviewCount: 142,
    features: ['Branding Kit', 'Keynote Stage', 'Media Backdrop', 'Networking Lounge']
  },
  {
    id: '16',
    title: 'Luxury Baby Shower Brunch',
    category: 'babyshower',
    description: 'Stylish brunch-format baby shower with premium décor accents and curated guest experiences.',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    price: 36000,
    duration: '4-5 hours',
    rating: 4.8,
    reviewCount: 96,
    features: ['Brunch Layout', 'Themed Décor', 'Photo Corner', 'Gift Registry Zone']
  },
  {
    id: '17',
    title: 'Convocation Celebration',
    category: 'graduation',
    description: 'Graduation-focused celebration with achievement wall, alumni moments, and family seating plans.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800',
    price: 32000,
    duration: '4-6 hours',
    rating: 4.6,
    reviewCount: 88,
    features: ['Achievement Display', 'Family Seating', 'Stage Moments', 'Photo Timeline']
  },
  {
    id: '18',
    title: 'Festive Sangeet Night',
    category: 'festival',
    description: 'High-energy sangeet and festive night planning with choreography zones and immersive lighting scenes.',
    image: 'https://images.unsplash.com/photo-1472653431158-6364773b2a56?w=800',
    price: 78000,
    duration: '5-7 hours',
    rating: 4.9,
    reviewCount: 149,
    features: ['Dance Floor Design', 'Lighting Sequences', 'Live Music Setup', 'Family Performance Flow']
  }
];
